---
abstract: 'output a DOM as HTML5'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  HTML::HTML5::Parser: 0
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-HTML5-Writer
no_index:
  directory:
    - inc
    - t
recommends:
  HTML::HTML5::Parser: 0
  HTML::HTML5::Sanity: 0
requires:
  Exporter: 0
  XML::LibXML: 1.60
  common::sense: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=HTML-HTML5-Writer
  homepage: http://search.cpan.org/dist/HTML-HTML5-Writer/
  license: http://dev.perl.org/licenses/
  repository: http://goddamn.co.uk/viewvc/perlmods/HTML-HTML5-Writer/
version: 0.04
